# Generated by Django 2.2 on 2019-06-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_email', models.CharField(default=None, max_length=50)),
                ('user_email', models.CharField(default=None, max_length=50)),
                ('appointment_date', models.CharField(default=None, max_length=50)),
                ('appointment_time', models.CharField(default=None, max_length=50)),
                ('name', models.CharField(default=None, max_length=50)),
                ('phone', models.CharField(default=None, max_length=15)),
                ('status', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('phone', models.CharField(default=None, max_length=15)),
                ('speciality', models.CharField(default=None, max_length=50)),
                ('qualification', models.CharField(default=None, max_length=50)),
                ('experience', models.IntegerField(default=0)),
                ('fee', models.IntegerField(default=0)),
                ('state', models.CharField(default=None, max_length=50)),
                ('city', models.CharField(default=None, max_length=50)),
                ('address', models.CharField(default=None, max_length=100)),
                ('photo', models.ImageField(default='default.png', upload_to='doctors_pics')),
                ('weekdays', models.CharField(default=None, max_length=100)),
                ('weekends', models.CharField(default=None, max_length=100)),
                ('weekdays_shift1_from', models.CharField(default=None, max_length=50)),
                ('weekdays_shift1_to', models.CharField(default=None, max_length=50)),
                ('weekdays_shift2_from', models.CharField(default=None, max_length=50)),
                ('weekdays_shift2_to', models.CharField(default=None, max_length=50)),
                ('weekends_shift1_from', models.CharField(default=None, max_length=50)),
                ('weekends_shift1_to', models.CharField(default=None, max_length=50)),
                ('weekends_shift2_from', models.CharField(default=None, max_length=50)),
                ('weekends_shift2_to', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
