# Generated by Django 2.2 on 2019-06-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_auto_20190603_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_email',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user_email',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
